### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by vishnu-m77** [vishnu-m77/DiffAPTOSC#19]
Check for unused parameters in the params.json file and remove them. Optimize the usage of the parameters in the files. Always pass the parameters specific to a certain model/function, example: params['dcg'], and use them within files as params (instead of using both 'config' and 'params').

**Comment by vishnu-m77** [comment]
Add some details in the ReadMe about how the parameters should be tweaked. Are there ways to improve the current implementation of parameters?

**Comment by vishnu-m77** [comment]
Parameters for number of images selected should be improved. 

- There should be one parameter `num_images` which gives the total number of images. 
- These images should then be split 70:10:20 into train, validation, and test. 
- Have a default minimum number of images. 
- Describe these requirements in the ReadMe
- Remove unnecessary parameters
- Experiment with the `batch size` and set rules about how that can vary.

**Comment by vishnu-m77** [comment]
Update README for #48

**Comment by vishnu-m77** [comment]
Images have to been sampled evenly from each class.

**Comment by Lakshay-G** [comment]
- `num_images` give total number of images
- Split 70:10:20 into train, validation, and test implemented
- Updated ReadME.md for #48 and added requirements.
- Minimum `num_images` is set to 1000, and mentioned in ReadMe.md as well

I have yet to look at unnecessary parameters.

**Comment by vishnu-m77** [comment]
Why is minimum `num_images` set to 1000? That looks way too high. It can be much smaller ~100.

**Comment by Lakshay-G** [comment]
- Removed `label_min_max` in `data` params, since its used in `DCG` params instead
- Removed `num_classes` in `data` params, since it's used in `DCG` params instead. Made changes accordingly in main.py
- Set minimum `num_images` to 100
