### ISSUE TITLE
Loss Plot

### ISSUE THREAD

**Issue by vishnu-m77** [vishnu-m77/DiffAPTOSC#38]
Why are you passing `xlabel="Epochs", ylabel="Loss"` in the `plot_loss` function?

**Comment by Sehmimul** [comment]
I didn't write that plot function...
@Lakshay-G  Please take a look

**Comment by Sehmimul** [comment]
Nevermind. I'll fix it in my commit. I'll remove those 2. It doesn't make any sense to pass a variable called 'Loss' in a plot loss function...

**Comment by Lakshay-G** [comment]
Don't we want the x and y axis of the plot to have some label?

**Comment by vishnu-m77** [comment]
You can define those values in the function. You don't have to pass them as parameters.

**Comment by Sehmimul** [comment]
> You can define those values in the function. You don't have to pass them as parameters.

yep. I'll make that change

**Comment by Lakshay-G** [comment]
I see, initially I was going to re-use the plot functions for accuracy as well, but didn't. Go ahead and remove them, thanks :)

**Comment by vishnu-m77** [comment]
Quick question: if the savedir does not exist, will the plot function work?

**Comment by Lakshay-G** [comment]
I'm not sure I understand the question clearly. `savedir` makes sure that the DCG and Diffusion loss plots are saved with correct names and in the plot directory. 

> Quick question: if the savedir does not exist, will the plot function work?

**Comment by vishnu-m77** [comment]
If the directory `plots` does not exist, will the plot function work?

**Comment by Lakshay-G** [comment]
It will work, we'd need to change the `savedir='plots/dcg_loss'` to `savedir='dcg_loss'` while passing them in the `plot_loss` function.

**Comment by vishnu-m77** [comment]
If you run the code without making any changes to it, and the `plots` directory does not exist, it will give an error, right? That implies there is a bug in the code. Please fix it so it won't give an error. 
Saving plots to the main folder is not ideal. We need the plots to be saved in the `plots` directory.

**Comment by Lakshay-G** [comment]
Nope. If you check the main.py, the `plots` directory will be automatically created if one does not exist, so there won't be any error.

**Comment by Sehmimul** [comment]
Yes I agree with Lakshay. Plots directory is created if not present: https://github.com/vishnu-m77/DiffAPTOSC/blob/main/main.py#L45

**Comment by vishnu-m77** [comment]
Cool, that works. It's not an ideal way of writing code because plots directory should not be created if there are no plots yet. For example, if we get error in diffusion, plots directory will be created but it will be empty. This does not affect functionality but its bad practice.
