### ISSUE TITLE
Find number of images of each label in entire dataset

### ISSUE THREAD

**Issue by Sehmimul** [vishnu-m77/DiffAPTOSC#45]
This is part of Dataloader. This information is extremely critical to work on https://github.com/vishnu-m77/DiffAPTOSC/issues/43

**Comment by Lakshay-G** [comment]
For train 2564 images:
- Label 0: 1250
- Label 1: 274
- Label 2: 685
- Label 3: 141
- Label 4: 214
For test 1098 images:
- Label 0: 555
- Label 1: 96
- Label 2: 314
- Label 3: 52
- Label 4: 81
For total 3662 images: 
- Label 0: 1805
- Label 1: 370
- Label 2: 999
- Label 3: 193
- Label 4: 295

**Comment by Sehmimul** [comment]
NIce! We will use the data for total images. So I guess branch out from latest version of test branch and then make a PR to test branch using the data you have from the total images
