### ISSUE TITLE
ReverseDiffusion initialized but unused

### ISSUE THREAD

**Issue by vishnu-m77** [vishnu-m77/DiffAPTOSC#50]
https://github.com/vishnu-m77/DiffAPTOSC/blame/e470627b16b643d3f89870ed42a3a2c10dc81029/src/diffusion.py#L272C5-L272C22

**Comment by Lakshay-G** [comment]
I think it's not used, we can remove it without any troubles. @Sehmimul can you also review it once you get time. Let me know if you also think we don't need it and I'll remove it then

**Comment by vishnu-m77** [comment]
Resolved in https://github.com/vishnu-m77/DiffAPTOSC/pull/51/commits/19cc7027c6da9f40c98f5da310f59466263e3d7f
